### ISSUE TITLE
Packaging just one of the solutions at a time, and any other external dependencies for tiles.

### ISSUE THREAD

**Issue by lancebitner** [SharePoint/sp-starter-kit#131]
**1. How do I just deploy/the tiles webpart?** 
Is there a way to package/deploy just the tiles, right now?  One problem for me is convincing my developers to put that many web parts in the environment. 40-fantastics is the only other package deal I am aware of but it is depreciated and many more parts which is even more problematic.

**2. Other than the Microsoft graph API, do the tiles have any other eternal dependency?** I am a contractor for the govt and pulling externally is a no go. I will have to rebuild the webpart so it has it internally, but Microsoft products are not open source so I will have to find something that is....any suggestions?

I did some custom sizing and multicolor layout for the tiles. The code is clean and simple. Some of the advantages of this tile layout as opposed to the "metro tiles" app found in the App store is the security, speed, AND the reusable-ness. I can use this framework webpart on any page, multiple times in all my site collections. It is not a one off thing connected to one list. 

![capturedd](https://user-images.githubusercontent.com/24795799/45003017-95a9c600-afab-11e8-9180-b9675c83e3bb.PNG)

**Comment by bcameron1231** [comment]
1. You absolutely can deploy just the tiles. Of course, it requires a bit of work to remove all the web parts you don't want. I would start by creating your own SPFx solution and slowly moving over the source code that is related to tiles, rather than stripping out all the features you don't want from the current source.

2. There are no dependencies on Microsoft Graph for the tiles web part, which means you could build this in a lower version of SPFx which isn't required for Targeted Release as well. It should be noted that SPFx uses a lot of dependencies to work (lots of node packages). It would be in your best interest to review these with your client and make sure nothing jumps out.

Unfortunately, we don't have explicit directions on how to isolate and package up the individual web parts.

**Comment by lancebitner** [comment]
Thanks that is what I will do this week; and good thing about the dependencies!

**Comment by bcameron1231** [comment]
@lancebitner  in the mean time, I just pulled the Tiles into their own solution to save you some work https://github.com/bcameron1231/SP-StarterKit-IsolatedTiles

I didn't do a bunch of testing, but I confirmed it was working

**Comment by lancebitner** [comment]
Yep - Perfect!

**Comment by lancebitner** [comment]
- I updated my Node.js to 10.17.0 and SPFx 1.9.1
- made sure npm outdated -g wasn't throwing any mismatches
- I updated my Node.js and SPFX
- I found I had more errors, so I installed gulp 3.9.1, I installed the latest node-gyp, and made sure my npm in my 'Program files' was up-to-date

Now I only have one error, Error - [tslint] No valid rules have been specified for TypeScript files. Here is the error on the workbench:

![tscerror](https://user-images.githubusercontent.com/24795799/71548847-2d41dd80-2982-11ea-81a1-f369f2721217.PNG)
![notslintrules](https://user-images.githubusercontent.com/24795799/71548852-3d59bd00-2982-11ea-875d-bea2a980dfcb.PNG)
