### ISSUE TITLE
SharePoint 2019 support ?

### ISSUE THREAD

**Issue by seaSide974** [SharePoint/sp-starter-kit#138]
#### Category
- [ X] Question
- [ ] Bug
- [X ] Enhancement

It would be great to support partially SharePoint 2019 :) A lot of customer are still on on premise and would like to benefit a more customized modern UI way,

Is it in roadmap ?

Thank you again for the work done

**Comment by eoverfield** [comment]
@seaSide974 since 2019 should have Communication and team sites, but as of now it will not support site designs, site scripts, or hub sites.

https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-2019-development-platform

You would also lose out on the graph calls. I cannot speak for the core team's plans, but my guess is too much of this project would be gutted to get it to work on 2019. You could port many of the webparts and extensions over, and some aspects of the provisioning should be helpful as well.

**Comment by bcameron1231** [comment]
Agreed with @eoverfield . I believe SP2019 is also shipping with 1.4x of SPFx. So you'll have to rebuild them, while also pulling out all of the Graph calls.

**Comment by seaSide974** [comment]
Alright :) Now that modern UI is coming on prem, it would be good to have the on premise mindset, , because a lot of developers work on premise (at least in France) too. In this way every customers could benefit PNP work if it was also compatible to 1.4.

I close the issue as you answered the compability question.

Thank you !
