### ISSUE TITLE
Can not use Apply-PnPProvisioningHierarchy

### ISSUE THREAD

**Issue by mukeshhope** [SharePoint/sp-starter-kit#212]
Hi Team,

I am not able to use this command
I tried to install latest version of SharePointPnPPowershellOnline using
Install-Module SharePointPnPPowershellOnline  
but when i write Apply-PnPProvisioningHierarchy
it throws error.
Please suggest what am i doing wrong. if i need the beeta version on pnppowershell online then how can i get that. error have been attached

Thanks
![error12](https://user-images.githubusercontent.com/18657453/49519456-04f2c700-f8c7-11e8-905f-0019efb02e31.png)

**Comment by bcameron1231** [comment]
Hi @mukeshhope when you installed the new module, did you remove the old module? In PowerShell, you can have multiple versions of modules installed on your OS. This can cause issues because the console may load the older version of your module which doesn't include this command.

Can you run this command and see if you have multiple showing up?

Get-Module SharePointPnPPowerShell* -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending

**Comment by mukeshhope** [comment]
Hi bcameron..,

Thankyou so much for your quick response. I have only one version of powershell.
 please have a look in the attached screen
![error13](https://user-images.githubusercontent.com/18657453/49522453-bbf24100-f8cd-11e8-8c66-705f80de46d4.png)

**Comment by bcameron1231** [comment]
Ah okay. Apply-PnPProvisioningHierarchy was deprecated and seems removed from 3.3.1811.0. It is still in the October release of 3.3.1810.0. 

In the notes, instead of using Apply-PnPProvisioningHierarchy, you should use Apply-PnPTenantTemplate.

**Comment by bcameron1231** [comment]
@VesaJuvonen Any ideas when the Starter Kit dev branch is going to be moved to master? Due to the November release of PnP PowerShell, there are some conflicting notes in the deployment documentation. 

Master branch docs say to use latest version of PnPPowerShell or a minimum version of 3.2.1810.0. But Apply-PnPProvisioningHierarchy was removed in the November release. Best advice going forward? Can I submit a PR for the current master branch to fix it, or will the dev be pushed into master soon?

**Comment by mukeshhope** [comment]
Hi @bcameron1231 ,

Thank you so much for your answer. i worked.
I installed 3.2.1810.0 and the command was there.
