### ISSUE TITLE
SharePoint App error - Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by Jenny-Neal** [SharePoint/sp-starter-kit#299]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

I have installed just the web parts using sharepoint-starter-kit.sppkg and add the Personal Calendar and Personal Email to a page in SharePoint.  I have then tested this in a web browser and the SharePoint app.

#### Observed Behavior

Both the Personal Calendar and Personal Email web parts are working correctly in a web browser but when viewing the page in the SharePoint app, I get the following error for the Personal Email web part and the Personal Calendar doesn't load.  

![Screenshot_20190626_165637](https://user-images.githubusercontent.com/49203815/60197700-c8bd8e80-9837-11e9-9987-349c50dabb77.jpg)

Unexpected token u in JSON at position 0

#### Steps to Reproduce

Installed sharepoint-starter-kit.sppkg as a SharePoint app in the admin center.
Given permission to the web parts via API management
Added web parts to SharePoint site page

**Comment by bcameron1231** [comment]
Hi @Jenny-Neal , It looks like this is a fairly old issue, is this still a problem for you? We are working back through the issues lists, and many updates were implemented since this ticket was submitted.

I am unable to reproduce with the latest solution. If this is still a problem for you, could you re-create the issue in the issue list and we'll make sure it's better tracked. Thanks!
