### ISSUE TITLE
error getting while running the script

### ISSUE THREAD

**Issue by raghu522** [SharePoint/sp-starter-kit#48]
<img width="935" alt="error" src="https://user-images.githubusercontent.com/30563384/41757007-05536206-75fd-11e8-8fe4-739842bb6125.png">
This is the error which I am getting.

**Comment by andreasblueher** [comment]
Hello @raghu522,

have you tried to connect to your tenant using [Connect-PnPOnline](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps)? To me it looks like there is an issue with that and that's required to work given the [instructions](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/connect-pnponline?view=sharepoint-ps).

**Comment by eoverfield** [comment]
And what version of PnP powershell are you running? A similar issue arose. 

https://github.com/SharePoint/sp-starter-kit/issues/49

**Comment by raghu522** [comment]
Yes I have connect my tenant using Connect-PnPOnline and version is:

Name                          Version
----                          -------
SharePointPnPPowerShellOnline 2.24.1803.0

**Comment by eoverfield** [comment]
Ah, that is the problem here. per the getting started instructions, https://github.com/SharePoint/sp-starter-kit#getting-started, you need to update PnP PowerShell. Please update to version  2.27.1806.1,
https://github.com/SharePoint/PnP-PowerShell/releases, and try the installation again.

When you update pnp ps, I suggest ensuring that 2.27.1806.1 is the only version installed before continuing with the starter kit install.

**Comment by raghu522** [comment]
Thanks a lot @eoverfield . it worked. I need few more suggestions, I didn't get siteprefix with my site it is showing contoso team site and pnp SP Starter kit. How can I remove this.
Another issue is, I have an intranet which I migrated from on prem to cloud last year. I want to deploy sp starter kit on that and make it with new look and feel, How can I make it default landing site (root site). Any suggestion?

**Comment by raghu522** [comment]
I got cleared myself for first issue, able to change site name and pnp  starter kit

**Comment by eoverfield** [comment]
@raghu522 regarding your second question, the starter kit is not necessarily designed to be applied to an existing site / portal. It should be possible to activate the SPFx solution so that the webparts and extensions are available on any given site though. If the existing sites are modern sites, you could also apply any of the provisioning templates.

As of today, you cannot reapply a site script I believe, so that might prove challenging. 

Summary: the starter kit is not designed to be applied to existing sites. It is possible, but outside the realm of this project. You can certainly use the code, concepts, patterns, and practices though to enable your own custom solution.

**Comment by bcameron1231** [comment]
Closing - Answered.
