### ISSUE TITLE
Error while running deploy.ps1

### ISSUE THREAD

**Issue by cknair** [SharePoint/sp-starter-kit#54]
![image](https://user-images.githubusercontent.com/40573489/41860353-66b7a7e6-7896-11e8-99a3-06d73d539f5f.png)
Hi , I am getting the above error while running deploy.ps1. It is not creating any site collections, but uploading site assets , images etc to the tenant admin site! I am behind a proxy, would that be the reason for New-PnPSite @hubParams  function to fail in deploy.ps1?

**Comment by eoverfield** [comment]
I believe the tenant url you are providing is your admin site, try again with -tenantUrl https://chikris.sharepoint.com (without -admin)

**Comment by cknair** [comment]
Thanks! 
Now I am stuck with provisioning step
![image](https://user-images.githubusercontent.com/40573489/41869136-fa1fe566-78af-11e8-8a51-2720016b083d.png) Teh user id Iam using is a tenant admin.

**Comment by bcameron1231** [comment]
@cknair  Did you make sure you follow through the deployment guidelines [here](https://github.com/SharePoint/sp-starter-kit)? 

If so, did you just create the app catalog? If so, you may need to wait a day for this to work correctly. Also is your tenant First Release for Everyone?

**Comment by eoverfield** [comment]
Also please check the pre-requirement that the account you using to deploy is also an admin for your term store. https://github.com/SharePoint/sp-starter-kit/#pre-requirements.

**Comment by Pharosz** [comment]
I went trough your list and all the requirements are in place, but have the same error + more:
Sorry cant attach picture...

Apply-PnPProvisioningTemplate : Access denied. You do not have permission to perform this action or access this
resource.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:123 char:1
+ Apply-PnPProvisioningTemplate -Path "$PSScriptRoot\portal.xml" -Param ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerUnauthorizedAccessException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate

Set-PnPSiteDesign : Cannot bind argument to parameter 'Identity' because it is null.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:128 char:29
+ Set-PnPSiteDesign -Identity $teamsitedesign -WebTemplate TeamSite
+                             ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-PnPSiteDesign], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SharePointPnP.PowerShell.Commands.SetSite
   Design

Set-PnPSiteDesign : Cannot bind argument to parameter 'Identity' because it is null.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:130 char:29
+ Set-PnPSiteDesign -Identity $communicationsitedesign -WebTemplate Com ...
+                             ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-PnPSiteDesign], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SharePointPnP.PowerShell.Commands.SetSite
   Design

Updating navigation and applying collab templates
Get-PnPProperty : Cannot bind argument to parameter 'ClientObject' because it is null.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:134 char:43
+ $children = Get-PnPProperty -ClientObject $departmentNode -Property C ...
+                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-PnPProperty], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,SharePointPnP.PowerShell.Commands.Base.En
   sureProperty

Cannot index into a null array.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:138 char:9
+         $node = Add-PnPNavigationNode -Location TopNavigationBar -Par ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

Cannot index into a null array.
At C:\Users\Pharosz\Documents\SPO Scripts\sp-starter-kit-master\provisioning\deploy.ps1:138 char:9
+         $node = Add-PnPNavigationNode -Location TopNavigationBar -Par ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

**Comment by eoverfield** [comment]
@Pharosz Is the first error the one you list, that started on line 123 of deploy.ps1? I have found with deploy.ps1, we want to always address the first error that appears as errors further on the may be caused by the same issue.

**Comment by Pharosz** [comment]
I have a warning before that, but yes this is the first error.

WARNING: You specified to remove existing content types for the list with url '/sites/demoportal/Lists/Alerts'. We
found a list with the same url in the site. In case of a list update we cannot remove existing content types as they
can be in use by existing list items and/or documents.

**Comment by eoverfield** [comment]
Could you also provide the full PS deploy command with the parameters you have set? You can X out the tenant name if you prefer.

Also, the credentials you are providing are tenant admin credentials? The provisioning template, portal.xml, includes the site scripts and site designs that require tenant admin permissions. otherwise, the rest of the template is setting site specific settings to the portal being created by the starter kit.

**Comment by Pharosz** [comment]
Its my private tenant for testing and playing around with the functions. I have only 1 account with global admin role.

[start_kit_pscript.txt](https://github.com/SharePoint/sp-starter-kit/files/2142702/start_kit_pscript.txt)

**Comment by eoverfield** [comment]
@Pharosz my suggestions:
Verify that the following three sites where created:
https://sharepointrobert.sharepoint.com/sites/demoportal
https://sharepointrobert.sharepoint.com/sites/demohr
https://sharepointrobert.sharepoint.com/sites/demomarketing
You might as well also check to see if they load for you in a browser.

Verify the .sppgk was successfully deployed to the tenant app catalog.

Check out the API permissions while you are at it in the new Preview Admin Center API Management.

If the above tests all check out, then I would run the following command after connect-pnponline of course. This will basically skip what should have already completed and start right around provivisioning portal.xml to the portal site.

.\deploy.ps1 -TenantUrl https://sharepointrobert.sharepoint.com -SitePrefix demo -SkipPowershellInstall -SkipSiteCreation -SkipSolutionDeployment

**Comment by Pharosz** [comment]
The sites are created however just as a regular sites. The sppgk is deployed.

The API permission is waiting to be approved but when I try to approve them it says: "[HTTP]:400 - Bad Request [CorrelationId]:d950759e-10fc-6000-1c7b-19a52f3ae455 [Version]:16.0.0.7813 - A service principal with the name SPFx-LOB-WebAPI could not be found." 

The same error for all in the list

**Comment by eoverfield** [comment]
They should be regular sites, or the portal home should be a comm site while the hr and marketing are modern team sites.
For API permissions, do not select the LOB ones, that is not yet active for the project.

**Comment by Pharosz** [comment]
Yes but I don't have any of the functionality that in the screenshots.

**Comment by bcameron1231** [comment]
@Pharosz  can you try to apply the portal template using PnP and see if you receive any errors? Using Apply-PnPProvisioningTemplate -Path "path/to/your/portal.xml" here the path maps to the portal.xml

**Comment by mag210** [comment]
Hi all, 

I have the same problem where I see multiple errors when the template is being applied. The first part of the script works okay and the sites are created. However, when the provisioning engine attempts to apply, I get a series of errors. I can confirm that the tenant is setup correctly. The SPKG file works and I can run the web parts without issue. The problem applies as soon as the script attempts to template the sites. 
![error](https://user-images.githubusercontent.com/15345746/42040666-0f51dfb8-7ae8-11e8-850b-ac42e2aa60c3.PNG)

**Comment by cknair** [comment]
Hi ,
Thanks for all your quick tips !
So this time I made sure I have met all pre-reqs correctly. Made tenant admin , a term store admin, created app catalog uploaded the spppkg file, made sure release preference is "targeted for everyone" waited more than 2 days and I tried deploy.ps1 today . I get the following error.
![image](https://user-images.githubusercontent.com/40573489/42111324-f7563086-7bdb-11e8-8486-0eb94dbaf9b5.png)

**Comment by eoverfield** [comment]
@cknair would you please verify the version of PnP PowerShell per a related post.
https://github.com/SharePoint/sp-starter-kit/issues/52#issuecomment-401322605

**Comment by cknair** [comment]
@eoverfield Here it is
![image](https://user-images.githubusercontent.com/40573489/42112741-c710a7bc-7be0-11e8-99d3-42c88358742b.png)

**Comment by eoverfield** [comment]
Ok, could you try turning more logging on and see if anything else pops out when you run deploy.ps1?

Set-PnPTraceLog -On -Level Debug

**Comment by cknair** [comment]
@eoverfield  here is the log..
![image](https://user-images.githubusercontent.com/40573489/42115969-2c1fb31c-7bed-11e8-9809-53c6d8af8b4d.png)

**Comment by Pharosz** [comment]
@bcameron1231 I didn't got any error.

**Comment by mag210** [comment]
@cknair I resolved this issue by upgrading to the latest version of PowerShell. (2.27.1806.1). You may want to try removing and reinstalling the PnP PowerShell library if your still seeing errors. To get things working here is a step by step of what I did:
1. Pulled in starter kit via Git
2. Made sure my tenant was set to first release (first release for entire tenant not just users)
3. Deployed spkg solution and made sure it was **not** set for tenant wide deployment.
4. Added in the property into the user profiles screen in the SP admin centre
5. Went into the new SP admin centre and granted permissions for apps to the Graph 
6. Updated to latest version of PowerShell and restarted
7. Ran PowerShell ISE (win 10) as admin and did a PnP connect to the root site collection for my dev tenant. 
8. Navigated to the saved starter kit in PowerShell and ran the deploy script. 
9. Starter kit site built and working including extensions and web parts. I did see an error on build, but this did not seem to affect the output, so wondering if its do with the stockmarket webpart.

Note: I was also promoted to authenticate again at least 2 times during the install.   

@eoverfield Is the step for including the API key for the stockmarket webpart a requirement for the solution or an option? The instructions aren't quite clear on this. I did not include the API key when I ran this and apart from an error on build, all is working. 

Thanks, 
-Max

**Comment by eoverfield** [comment]
@mag210  thank you for the steps that worked for you.

Regarding the api key, if you do not provide one, the deployment script ignores this and carries on without an additional message or warning. If a stock api key is provided, then the deployment script simply stores the key in a tenant property, with key name "PnP-Portal-AlphaVantage-API-Key"

**Comment by eoverfield** [comment]
Closing as a stale issue, also addressed with newer provisioning methodology.
